version: 2
jobs:
  build:
    machine: true
    image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - run:
          command: |  # use pipenv to install dependencies
            pip install robotframework
            pip install robotframework-browser
            pip install psycopg2
            rfbrowser init
            robot -d ./logs tests\