version: 2
jobs:
  build:
    machine: true
    image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - run: pip install --upgrade pip
      - run: pip install robotframework-browser
      - run: pip install psycopg2
      - run: rfbrowser init
      - run: robot -d ./logs tests\